name: dtcc_task
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  avatar_stack: ^1.2.0
  flutter:
    sdk: flutter
  freezed: ^2.5.0
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  mirai: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Figtree
      fonts:
        - asset: assets/fonts/Figtree-Light.ttf
          weight: 300
        - asset: assets/fonts/Figtree-Regular.ttf
          weight: 400
        - asset: assets/fonts/Figtree-Medium.ttf
          weight: 500
        - asset: assets/fonts/Figtree-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Figtree-Bold.ttf
          weight: 700
        - asset: assets/fonts/Figtree-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Figtree-Black.ttf
          weight: 900
